import type { Metadata } from "next";
import { Aboreto, DM_Sans, Allura } from "next/font/google";
import "./globals.css";
import Footer from "./Footer";
import Header from "./Header";
import { Toaster } from "../components/ui/Toaster";

const aboreto = Aboreto({
  variable: "--font-aboreto",
  subsets: ["latin"],
  weight: "400"
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const allura = Allura({
  variable: "--font-dancing-script",
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${aboreto.variable} ${dmSans.variable} ${allura.variable} antialiased min-h-screen flex flex-col font-dm-sans`}
      >
        <Header />
        <main className="flex-grow mb-20">{children}</main>
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
